### ISSUE TITLE
KeyError: 'chrom'

### ISSUE THREAD

**Issue by Bonder-MJ** [davidaknowles/leafcutter#21]
Hi,

When trying to prepare the leafcutt cluster output to run a splice QTL analysis I get the following error:

Traceback (most recent call last):
  File "../scripts/prepare_phenotype_table.py", line 166, in <module>
    main(args[0], int(options.npcs) )
  File "../scripts/prepare_phenotype_table.py", line 58, in main
    chrom = dic['chrom'].replace("chr",'')
KeyError: 'chrom'

What can cause this error?

Cheers,
Marc

**Comment by goldenflaw** [comment]
Hi Marc, could you check that you have the correct input?

Yang

**Comment by Bonder-MJ** [comment]
Hi Yang,

Thanks for the reply. I used exactly the commands as presented in the
example.

Cheers,
Marc

**Comment by Bonder-MJ** [comment]
Hi Yang,

I try to put in the "testYRIvsEU_perind_numers.counts.gz" file.
Which were generated using: python ../clustering/leafcutter_cluster.py -j
test_juncfiles.txt -m 50 -o testYRIvsEU -l 500000

The first two rows look like this:

RNA.NA06986_CEU.chr1.bam RNA.NA06994_CEU.chr1.bam RNA.NA18486_YRI.chr1.bam
RNA.NA06985_CEU.chr1.bam RNA.NA18487_YRI.chr1.bam RNA.NA06989_CEU.chr1.bam
RNA.NA06984_CEU.chr1.bam RNA.NA18488_YRI.chr1.bam RNA.NA18489_YRI.chr1.bam
RNA.NA18498_YRI.chr1.bam
chr1:17055:17233:clu_1 21 13 18 20 17 12 11 8 15 25

Cheers,
Marc

**Comment by Bonder-MJ** [comment]
Hi Yang,

I just added an extra column name "chrom" to the first line of the output.
That seems to solve the issue on row 58.
However, now I get an error on row 69, were it tries to split on  '/'

Am I using the wrong file or is the output of the first step of the script
changed?
Thanks!

Cheers,
Marc

**Comment by goldenflaw** [comment]
Hi Marc,

You have to put the _counts file (the other output from leafcutter).

Yang

**Comment by Bonder-MJ** [comment]
Thanks! Maybe change the example in the readme. That is why I tried to put
in the wrong file.

Regards,
Marc

**Comment by davidaknowles** [comment]
This is now fixed in the readme, sorry for the inconvenience and thanks for finding this issue!

**Comment by summike** [comment]
**Hi, I am sorry that I met the similar problem when I ran my own data. There are about 350 samples in my data, so I cannot provide the comprehensive information on the first two rows, but I try to provide as much as I can. Please kindly see the details below.
Here is my TT_perind.counts file,**

chrom	KDNY048-Aligned.out.bam	ABO8T90-Aligned.out.bam	ABT3R48-Aligned.out.bam	ABE3T55-Aligned.out.bam	ABP9U87-Aligned.out.bam	44ad-0cb35529f2-Aligned.out.bam	ABD9C13-Aligned.out.bam	ABF4J93-Aligned.out.bam	9d55-8ac6e18fcd-Aligned.out.bam ...
chr1:15225:185747:clu_2911_NA	3/3	0/1	53/54	2/2	0/0	0/0	0/0	8/9 0/0 ...
chr1:15225:185758:clu_2911_NA	0/3	1/1	1/54	0/2	0/0	0/0	0/0	1/9	0/0 ...
...

**After I ran the command,**
"python scripts/prepare_phenotype_table.py example_data/TT_perind.counts.gz -p 10".

**I got the following error,**
"
Starting...
Traceback (most recent call last):
File "scripts/prepare_phenotype_table.py", line 171, in 
main(args[0], int(options.npcs) )
File "scripts/prepare_phenotype_table.py", line 60, in main
chrom = dic['chrom'].replace("chr",'')
KeyError: 'chrom'
"

**I am clear that I input the _counts file and have already sorted by the first column (chrom). May I know what may cause this error?**

**Thank you for your patience and kind help!**

**Comment by goldenflaw** [comment]
It's hard to tell, could you try running python2 script/...

Yang

**Comment by summike** [comment]
Hello Yang,
Thank you very much for your reply. However, the error still occurs after taking your advice. 

command of Line 60, chrom = dic['chrom'].replace("chr",''),  is located in one for-loop. I am sorry that my python knowledge is limited. May I know does this command for extract the chromosome number without 'chr'?
<img width="535" alt="2018-07-16 6 43 27" src="https://user-images.githubusercontent.com/28684936/42774087-b594d8b4-8928-11e8-8770-b784e53adb6c.png">

**Comment by goldenflaw** [comment]
Hello,

Are you sure your ratio file is gzipped? If so, I would add a line ("print
dic") right before chrom = dic['chrom'].replace("chr",''), and report back.

Best,
Yang

**Comment by summike** [comment]
Hello Yang,
I have a check of the 'dic' file. There must be something gone wrong in the previous steps as the format is not as nice and clear as that of the example data you provided. I will re-run the whole process again to see if I can address this problem.
Thank you for your help!

Best wishes,
Mike

**Comment by summike** [comment]
Hello Yang,
Problem solved!

The mistake was made when I did the data selection process. I mistakenly separated each datum by "\t" other than " " in the gzipped file.

Thank you very much for your help!
Best wishes,
Mike
